version: "3.8"

services:
  frontend:
    build:
      context: ./micro-blog
      dockerfile: Dockerfile
    container_name: micowb-frontend
    environment:
      VITE_API_TARGET: http://host.docker.internal:8005
    ports:
      - "5173:5173"
